version: '3'
services:
  postgres:
    container_name: event-app-postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    ports:
      - '5432:5432'
    env_file:
      - .env.development
